modules_dir = "artifacts/"

[[module]]
    name = "records_effector"
    max_heap_size = "10 KiB"
    logger_enabled = true

[[module]]
    name = "records_pure"
    max_heap_size = "10 KiB"
    logger_enabled = true
