[package]
name = "record-effector"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "records_effector"
path = "src/main.rs"

[dependencies]
fluence = { version = "=0.5.0", features = ["logger"]}
test-record = { path = "../test-record" }
