[package]
name = "wasm-greeting"
version = "0.1.0"
authors = ["Fluence Labs"]
description = "The greeting module for the Fluence network"
edition = "2021"
publish = false

[[bin]]
name = "greeting"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.10.0"
