[package]
name = "wasm-greeting"
version = "0.1.0"
authors = ["Fluence Labs"]
description = "The greeting module for the Fluence network"
repository = "https://github.com/fluencelabs/marine/tree/master/examples/greeting"
edition = "2018"
publish = false

[[bin]]
name = "greeting"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.7.0"

[dev-dependencies]
marine-rs-sdk-test = "0.4.1"
