[package]
name = "test-record"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[lib]
name = "test_record"
path = "src/test_record.rs"

[dependencies]
marine-rs-sdk = "0.9.0"
