[package]
name = "call_parameters"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "call_parameters"
path = "src/main.rs"

[dependencies]
marine-rs-sdk ="0.6.13"

[dev-dependencies]
marine-rs-sdk-test = "0.3.0"
