[package]
name = "call_parameters"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "call_parameters"
path = "src/main.rs"

[dependencies]
fluence = "0.6.9"

[dev-dependencies]
fluence-test = "0.1.7"
