[package]
name = "shrek"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[[bin]]
path = "src/main.rs"
name = "shrek"

[dependencies]
marine-rs-sdk ={ version = "0.10.0", features = ["logger"] }
