[package]
name = "facade"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[[bin]]
name = "facade"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version = "0.12.0", features = ["logger"] }
anyhow = "1.0.31"
log = "0.4.8"
