[package]
name = "local_storage"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[[bin]]
name = "local_storage"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version = "0.11.0", features = ["logger"] }
wasm-tracing-allocator = "0.1.0"

log = "0.4.8"
