[package]
name = "local_storage"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "local_storage"
path = "src/main.rs"

[dependencies]
fluence = { version = "=0.4.1", features = ["logger"]}
log = "0.4.8"
