[package]
name = "multiservice-marine-test"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = { workspace = true }
publish = false

[dependencies]

[dev-dependencies]
marine-rs-sdk-test = "0.8.1"
