[package]
name = "wasm-sqlite-test"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "sqlite_test"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.7.0"
marine-sqlite-connector = "0.6.0"
