[package]
name = "wasm-failing"
version = "0.1.0"
authors = ["Fluence Labs"]
description = "The failing module for the Fluence network"
edition = "2021"
publish = false

[[bin]]
name = "failing"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.12.0"
