[package]
name = "record-pure"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[[bin]]
name = "records_pure"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.14.0"
test-record = { path = "../test-record" }
